export const LOAD_GEO_DATA = "LOAD_GEO_DATA";
export const SUCCESS_GEO_DATA = "SUCCESS_GEO_DATA";
export const FAIL_GEO_DATA = "FAIL_GEO_DATA";
export const VISIBLE_GEO_DATA = "VISIBLE_GEO_DATA";
export const FILTER_GEO_DATA = "FILTER_GEO_DATA";

export const LOAD_CITIES_GEO_DATA = "LOAD_CITIES_GEO_DATA";
export const SUCCESS_CITIES_GEO_DATA = "SUCCESS_CITIES_GEO_DATA";
export const FAIL_CITIES_GEO_DATA = "FAIL_CITIES_GEO_DATA";
export const VISIBLE_CITIES_GEO_DATA = "VISIBLE_CITIES_GEO_DATA";
export const FILTER_CITIES_GEO_DATA = "FILTER_CITIES_GEO_DATA";

export const CHANGE_BASEMAP = "CHANGE_BASEMAP";
export const CHANGE_VIS_BASEMAP = "CHANGE_VIS_BASEMAP";

export const UPDATE_LAYER_STYLE = "UPDATE_LAYER_STYLE";

export const ZOOM_OBJECT = "ZOOM_OBJECT";

export const SHOW_EDIT = "SHOW_EDIT";
